In [1]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np
import jieba

In [ ]:
sentence = "我喜歡閱讀書籍，也喜歡使用電腦來學習新的知識"

In [3]:
words = list(jieba.cut(sentence))

In [5]:
words_array = np.array(words).reshape(-1, 1)

In [7]:
onehot_encoder = OneHotEncoder(sparse_output=False)

In [ ]:
onehot_encoded = onehot_encoder.fit_transform(words_array)

In [11]:
print(onehot_encoder.categories_)

[array(['也', '使用', '喜歡', '學習', '我', '新', '書籍', '的', '知識', '閱讀', '電腦來', '，'],
      dtype='<U3')]


In [13]:
print(onehot_encoded)

[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]


In [14]:
# 找出「我」的 One-Hot Encoding
print(onehot_encoded[0,:])

# 找出「喜歡」的 One-Hot Encoding
print(onehot_encoded[2,:])

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
